/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.recibo;

import java.awt.CardLayout;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Lanix
 */
public class ConceptoForm extends javax.swing.JPanel {

    /**
     * Creates new form Concepto
     */
    public ConceptoForm() {
        initComponents();
        CardLayout card = (CardLayout)Precio.getLayout();
        card.show(Precio, "card2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdConcepto = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        cmbProductoServicio = new javax.swing.JComboBox<>();
        Precio = new javax.swing.JPanel();
        txtPrecioUnitario = new javax.swing.JLabel();
        spnNuevoPrecio = new javax.swing.JSpinner();
        chkNuevoPrecio = new javax.swing.JCheckBox();
        txtSubtotal = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        txtIdConcepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIdConcepto.setText("ID");
        add(txtIdConcepto);

        spnCantidad.setModel(new SpinnerNumberModel(1,1,10000,1));
        add(spnCantidad);

        add(cmbProductoServicio);

        Precio.setOpaque(false);
        Precio.setLayout(new java.awt.CardLayout());

        txtPrecioUnitario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        txtPrecioUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecioUnitario.setText("Precio unitario");
        Precio.add(txtPrecioUnitario, "card2");

        spnNuevoPrecio.setModel(new SpinnerNumberModel(0.0,0.0,50000,1.5));
        Precio.add(spnNuevoPrecio, "card3");

        add(Precio);

        chkNuevoPrecio.setOpaque(false);
        chkNuevoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNuevoPrecioActionPerformed(evt);
            }
        });
        add(chkNuevoPrecio);

        txtSubtotal.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        txtSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSubtotal.setText("SubTotal");
        add(txtSubtotal);

        btnEliminar.setText("Eliminar");
        add(btnEliminar);
    }// </editor-fold>//GEN-END:initComponents

    public void changeCard3(){
        CardLayout card = (CardLayout)Precio.getLayout();
        
        card.show(Precio, "card3");
    }
    
    private void chkNuevoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNuevoPrecioActionPerformed
        //IF CHECK nuevoPrecio -> MOSTRAR card3
        CardLayout card = (CardLayout)Precio.getLayout();
        if(chkNuevoPrecio.isSelected()){
            card.show(Precio, "card3");
        }
        else{
            card.show(Precio, "card2");
        }
    }//GEN-LAST:event_chkNuevoPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Precio;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JCheckBox chkNuevoPrecio;
    public javax.swing.JComboBox<String> cmbProductoServicio;
    public javax.swing.JSpinner spnCantidad;
    public javax.swing.JSpinner spnNuevoPrecio;
    public javax.swing.JLabel txtIdConcepto;
    public javax.swing.JLabel txtPrecioUnitario;
    public javax.swing.JLabel txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
