package view.cliente;

public class ClientesForm extends javax.swing.JPanel {
    public static enum formType {SIGNUP,UPDATE};
    public formType type;
    
    public ClientesForm(formType type) {
        initComponents();
        this.type = type;
        
        switch(type){
            case SIGNUP:{
                setViewToSignUp();
                break;
            }
            case UPDATE:{
                setViewToModify();
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblTitulo = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Botones = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnRegistrar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCancelar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Formulario = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Campos = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtPaterno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtMaterno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioHombre = new javax.swing.JRadioButton();
        radioMujer = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        txtRFC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtRegimen = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtCelular = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtContraseñaSat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtComentarios = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setOpaque(false);
        Titulo.setLayout(new javax.swing.BoxLayout(Titulo, javax.swing.BoxLayout.LINE_AXIS));
        Titulo.add(filler8);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTitulo.setText("REGISTRO DE CLIENTE");
        Titulo.add(lblTitulo);
        Titulo.add(filler9);

        Botones.setOpaque(false);
        Botones.setLayout(new javax.swing.BoxLayout(Botones, javax.swing.BoxLayout.LINE_AXIS));
        Botones.add(filler10);

        btnRegistrar.setText("Registrar");
        Botones.add(btnRegistrar);
        Botones.add(filler1);

        btnCancelar.setText("Cancelar");
        Botones.add(btnCancelar);
        Botones.add(filler2);

        Formulario.setOpaque(false);
        Formulario.setLayout(new javax.swing.BoxLayout(Formulario, javax.swing.BoxLayout.LINE_AXIS));
        Formulario.add(filler3);

        Campos.setOpaque(false);
        Campos.setLayout(new java.awt.GridLayout(4, 3, 20, 10));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setOpaque(false);
        jPanel5.add(txtNombre);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nombre*");
        jPanel5.add(jLabel9);

        Campos.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        txtPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaterno.setOpaque(false);
        jPanel6.add(txtPaterno);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Paterno*");
        jPanel6.add(jLabel16);

        Campos.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        txtMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaterno.setOpaque(false);
        jPanel7.add(txtMaterno);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Materno*");
        jPanel7.add(jLabel17);

        Campos.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel18.setText("Sexo:");
        jPanel8.add(jLabel18);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        Sexo.add(radioHombre);
        radioHombre.setSelected(true);
        radioHombre.setText("Hombre");
        radioHombre.setOpaque(false);
        jPanel1.add(radioHombre);

        Sexo.add(radioMujer);
        radioMujer.setText("Mujer");
        radioMujer.setOpaque(false);
        jPanel1.add(radioMujer);

        jPanel8.add(jPanel1);

        Campos.add(jPanel8);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        txtRFC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRFC.setOpaque(false);
        jPanel9.add(txtRFC);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("RFC*");
        jPanel9.add(jLabel19);

        Campos.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        txtRegimen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRegimen.setOpaque(false);
        jPanel10.add(txtRegimen);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Régimen Fiscal*");
        jPanel10.add(jLabel20);

        Campos.add(jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(2, 1));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setOpaque(false);
        jPanel11.add(txtEmail);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("E-mail");
        jPanel11.add(jLabel21);

        Campos.add(jPanel11);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setOpaque(false);
        jPanel12.add(txtTelefono);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Teléfono");
        jPanel12.add(jLabel22);

        Campos.add(jPanel12);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(2, 1));

        txtCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCelular.setOpaque(false);
        jPanel13.add(txtCelular);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Celular");
        jPanel13.add(jLabel23);

        Campos.add(jPanel13);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(2, 1));

        txtContraseñaSat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseñaSat.setOpaque(false);
        jPanel14.add(txtContraseñaSat);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Contraseña SAT");
        jPanel14.add(jLabel24);

        Campos.add(jPanel14);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(2, 1));

        txtComentarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComentarios.setOpaque(false);
        jPanel15.add(txtComentarios);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Comentarios");
        jPanel15.add(jLabel25);

        Campos.add(jPanel15);

        Formulario.add(Campos);
        Formulario.add(filler4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setViewToSignUp(){        
        this.lblTitulo.setText("REGISTRO DE CLIENTE");
        this.btnRegistrar.setText("Registrar");
    }
    
    private void setViewToModify(){
        this.lblTitulo.setText("MODIFICACIÓN DE CLIENTE");
        this.txtRFC.setEditable(false);
        this.btnRegistrar.setText("Modificar");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Campos;
    private javax.swing.JPanel Formulario;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JPanel Titulo;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JRadioButton radioHombre;
    public javax.swing.JRadioButton radioMujer;
    public javax.swing.JTextField txtCelular;
    public javax.swing.JTextField txtComentarios;
    public javax.swing.JTextField txtContraseñaSat;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtMaterno;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPaterno;
    public javax.swing.JTextField txtRFC;
    public javax.swing.JTextField txtRegimen;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
