package view.documento;

public class DocumentosForm extends javax.swing.JPanel {
    public static enum formType {SIGNUP,UPDATE};
    public formType type;
    
    public DocumentosForm(formType type) {
        initComponents();
        this.type = type;
        
        switch(type){
            case SIGNUP:{
                setViewToSignUp();
                break;
            }
            case UPDATE:{
                setViewToModify();
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblTitulo = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Botones = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAgregar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCancelar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Centro = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblArchivo = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaExpedicion = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaExpiracion = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtContrasegna = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setOpaque(false);
        Titulo.setLayout(new javax.swing.BoxLayout(Titulo, javax.swing.BoxLayout.LINE_AXIS));
        Titulo.add(filler1);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTitulo.setText("AGREGAR DOCUMENTO");
        Titulo.add(lblTitulo);
        Titulo.add(filler2);

        Botones.setOpaque(false);
        Botones.setLayout(new javax.swing.BoxLayout(Botones, javax.swing.BoxLayout.LINE_AXIS));
        Botones.add(filler3);

        btnAgregar.setText("Agregar");
        Botones.add(btnAgregar);
        Botones.add(filler4);

        btnCancelar.setText("Cancelar");
        Botones.add(btnCancelar);
        Botones.add(filler5);

        Centro.setOpaque(false);
        Centro.setLayout(new javax.swing.BoxLayout(Centro, javax.swing.BoxLayout.LINE_AXIS));

        Form.setOpaque(false);
        Form.setLayout(new java.awt.GridLayout(0, 1, 20, 10));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        lblArchivo.setText("Archivo*:");
        jPanel2.add(lblArchivo);

        txtFilePath.setEditable(false);
        jPanel2.add(txtFilePath);

        btnFileChooser.setText("...");
        jPanel2.add(btnFileChooser);

        Form.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Tipo documento:");
        jPanel3.add(jLabel2);

        jPanel3.add(cmbTipoDocumento);

        Form.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Cliente*:");
        jPanel4.add(jLabel3);

        txtCliente.setOpaque(false);
        jPanel4.add(txtCliente);

        Form.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Fecha expedición*:");
        jPanel5.add(jLabel4);

        txtFechaExpedicion.setOpaque(false);
        jPanel5.add(txtFechaExpedicion);

        Form.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setText("Fecha expiración*:");
        jPanel6.add(jLabel5);

        txtFechaExpiracion.setOpaque(false);
        jPanel6.add(txtFechaExpiracion);

        Form.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setText("Contraseña:");
        jPanel7.add(jLabel6);

        txtContrasegna.setOpaque(false);
        jPanel7.add(txtContrasegna);

        Form.add(jPanel7);

        Centro.add(Form);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Centro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Centro, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setViewToSignUp(){        
        this.lblTitulo.setText("AGREGAR DOCUMENTO");
        this.btnAgregar.setText("Agregar");
    }
    
    private void setViewToModify(){
        this.lblTitulo.setText("MODIFICACIÓN DE DOCUMENTO");
        this.btnAgregar.setText("Modificar");
        this.lblArchivo.setText("Nuevo archivo:");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Titulo;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnFileChooser;
    public javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JLabel lblArchivo;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextField txtContrasegna;
    public com.toedter.calendar.JDateChooser txtFechaExpedicion;
    public com.toedter.calendar.JDateChooser txtFechaExpiracion;
    public javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables
}
