/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cliente;

/**
 *
 * @author Lanix
 */
public class ClienteInfo extends javax.swing.JPanel {

    /**
     * Creates new form ClienteInfo
     */
    public ClienteInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        Botones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        Info = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegimen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFechaActualizacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MasInfo = new javax.swing.JPanel();
        Modulos = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setOpaque(false);
        Titulo.setLayout(new javax.swing.BoxLayout(Titulo, javax.swing.BoxLayout.LINE_AXIS));
        Titulo.add(filler2);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("INFORMACIÓN DE CLIENTE");
        Titulo.add(jLabel1);
        Titulo.add(filler1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        Botones.setOpaque(false);
        Botones.setLayout(new javax.swing.BoxLayout(Botones, javax.swing.BoxLayout.Y_AXIS));

        btnRegresar.setText("Regresar");
        Botones.add(btnRegresar);
        Botones.add(filler3);

        jPanel2.add(Botones);

        Info.setOpaque(false);
        Info.setLayout(new java.awt.GridLayout(0, 4, 20, 10));

        jLabel2.setText("Nombre:");
        Info.add(jLabel2);

        txtNombre.setEditable(false);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.setOpaque(false);
        Info.add(txtNombre);

        jLabel5.setText("Sexo:");
        Info.add(jLabel5);

        txtSexo.setEditable(false);
        txtSexo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSexo.setOpaque(false);
        Info.add(txtSexo);

        jLabel6.setText("RFC:");
        Info.add(jLabel6);

        txtRFC.setEditable(false);
        txtRFC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRFC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRFC.setOpaque(false);
        Info.add(txtRFC);

        jLabel7.setText("Régimen fiscal:");
        Info.add(jLabel7);

        txtRegimen.setEditable(false);
        txtRegimen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRegimen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRegimen.setOpaque(false);
        Info.add(txtRegimen);

        jLabel8.setText("E-mail:");
        Info.add(jLabel8);

        txtEmail.setEditable(false);
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmail.setOpaque(false);
        Info.add(txtEmail);

        jLabel9.setText("Teléfono:");
        Info.add(jLabel9);

        txtTelefono.setEditable(false);
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefono.setOpaque(false);
        Info.add(txtTelefono);

        jLabel10.setText("Celular:");
        Info.add(jLabel10);

        txtCelular.setEditable(false);
        txtCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCelular.setOpaque(false);
        Info.add(txtCelular);

        jLabel11.setText("Contraseña SAT:");
        Info.add(jLabel11);

        txtContraseña.setEditable(false);
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtContraseña.setOpaque(false);
        Info.add(txtContraseña);

        jLabel12.setText("Fecha actualización datos:");
        Info.add(jLabel12);

        txtFechaActualizacion.setEditable(false);
        txtFechaActualizacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaActualizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFechaActualizacion.setOpaque(false);
        Info.add(txtFechaActualizacion);

        jLabel13.setText("Comentarios:");
        Info.add(jLabel13);

        txtComentarios.setEditable(false);
        txtComentarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtComentarios.setOpaque(false);
        Info.add(txtComentarios);

        jPanel2.add(Info);

        MasInfo.setOpaque(false);
        MasInfo.setLayout(new javax.swing.BoxLayout(MasInfo, javax.swing.BoxLayout.Y_AXIS));
        MasInfo.add(Modulos);

        jScrollPane1.setViewportView(MasInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Info;
    public javax.swing.JPanel MasInfo;
    public javax.swing.JTabbedPane Modulos;
    private javax.swing.JPanel Titulo;
    public javax.swing.JButton btnRegresar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtCelular;
    public javax.swing.JTextField txtComentarios;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFechaActualizacion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtRFC;
    public javax.swing.JTextField txtRegimen;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
