package view.empleado;

import javax.swing.SpinnerNumberModel;

public class EmpleadosForm extends javax.swing.JPanel {
    public static enum formType {SIGNUP,UPDATE};
    public formType type;
    
    public EmpleadosForm(formType type) {
        initComponents();
        this.type = type;
        
        switch(type){
            case SIGNUP:{
                setViewToSignUp();
                break;
            }
            case UPDATE:{
                setViewToModify();
                break;
            }
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblTitulo = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Campos = new javax.swing.JPanel();
        IdEmpleado = new javax.swing.JPanel();
        txtIdEmpleado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Nombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Paterno = new javax.swing.JPanel();
        txtPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Materno = new javax.swing.JPanel();
        txtMaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PanelSexo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioM = new javax.swing.JRadioButton();
        radioH = new javax.swing.JRadioButton();
        Puesto = new javax.swing.JPanel();
        txtPuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Horario = new javax.swing.JPanel();
        txtHorario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Salario = new javax.swing.JPanel();
        spnSalario = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        FechaAlta = new javax.swing.JPanel();
        dateFechaAlta = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        Estado = new javax.swing.JPanel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Botones = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnRegistrar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCancelar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setOpaque(false);
        Titulo.setLayout(new javax.swing.BoxLayout(Titulo, javax.swing.BoxLayout.X_AXIS));
        Titulo.add(filler1);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTitulo.setText("REGISTRO DE EMPLEADO");
        Titulo.add(lblTitulo);
        Titulo.add(filler2);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));
        jPanel2.add(filler6);

        Campos.setOpaque(false);
        Campos.setLayout(new java.awt.GridLayout(5, 2, 20, 10));

        IdEmpleado.setOpaque(false);
        IdEmpleado.setLayout(new java.awt.GridLayout(2, 1));

        txtIdEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIdEmpleado.setText("n");
        IdEmpleado.add(txtIdEmpleado);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Id Empleado");
        IdEmpleado.add(jLabel10);

        Campos.add(IdEmpleado);
        IdEmpleado.setVisible(false);

        Nombre.setOpaque(false);
        Nombre.setLayout(new java.awt.GridLayout(2, 1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        Nombre.add(txtNombre);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(txtNombre);
        jLabel1.setText("Nombre");
        Nombre.add(jLabel1);

        Campos.add(Nombre);

        Paterno.setOpaque(false);
        Paterno.setLayout(new java.awt.GridLayout(2, 1));

        txtPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Paterno.add(txtPaterno);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(txtPaterno);
        jLabel2.setText("Paterno");
        Paterno.add(jLabel2);

        Campos.add(Paterno);

        Materno.setOpaque(false);
        Materno.setLayout(new java.awt.GridLayout(2, 1));

        txtMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Materno.add(txtMaterno);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(txtMaterno);
        jLabel3.setText("Materno");
        Materno.add(jLabel3);

        Campos.add(Materno);

        PanelSexo.setOpaque(false);
        PanelSexo.setLayout(new javax.swing.BoxLayout(PanelSexo, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Sexo:");
        PanelSexo.add(jLabel4);

        jPanel1.setOpaque(false);

        Sexo.add(radioM);
        radioM.setText("Mujer");
        radioM.setOpaque(false);

        Sexo.add(radioH);
        radioH.setSelected(true);
        radioH.setText("Hombre");
        radioH.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioH)
                    .addComponent(radioM))
                .addContainerGap())
        );

        PanelSexo.add(jPanel1);

        Campos.add(PanelSexo);

        Puesto.setOpaque(false);
        Puesto.setLayout(new java.awt.GridLayout(2, 1));

        txtPuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Puesto.add(txtPuesto);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(txtPuesto);
        jLabel5.setText("Puesto");
        Puesto.add(jLabel5);

        Campos.add(Puesto);

        Horario.setOpaque(false);
        Horario.setLayout(new java.awt.GridLayout(2, 1));

        txtHorario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Horario.add(txtHorario);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setLabelFor(txtHorario);
        jLabel6.setText("Horario");
        Horario.add(jLabel6);

        Campos.add(Horario);

        Salario.setOpaque(false);
        Salario.setLayout(new java.awt.GridLayout(2, 1));

        spnSalario.setModel(new SpinnerNumberModel(0.00,0.00,10000.00,1.00));
        Salario.add(spnSalario);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salario ($/h)");
        Salario.add(jLabel7);

        Campos.add(Salario);

        FechaAlta.setOpaque(false);
        FechaAlta.setLayout(new java.awt.GridLayout(2, 1));
        FechaAlta.add(dateFechaAlta);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fecha alta");
        FechaAlta.add(jLabel8);

        Campos.add(FechaAlta);

        Estado.setOpaque(false);
        Estado.setLayout(new java.awt.GridLayout(2, 1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Desactivado" }));
        Estado.add(cmbEstado);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setLabelFor(cmbEstado);
        jLabel9.setText("Estado");
        Estado.add(jLabel9);

        Campos.add(Estado);

        jPanel2.add(Campos);
        jPanel2.add(filler7);

        Botones.setOpaque(false);
        Botones.setLayout(new javax.swing.BoxLayout(Botones, javax.swing.BoxLayout.X_AXIS));
        Botones.add(filler3);

        btnRegistrar.setText("Registrar");
        Botones.add(btnRegistrar);
        Botones.add(filler5);

        btnCancelar.setText("Cancelar");
        Botones.add(btnCancelar);
        Botones.add(filler4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void setViewToSignUp(){        
        this.lblTitulo.setText("REGISTRO DE EMPLEADO");
        this.btnRegistrar.setText("Registrar");
    }
    
    private void setViewToModify(){
        this.lblTitulo.setText("MODIFICACIÓN DE EMPLEADO");
        this.btnRegistrar.setText("Modificar");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Campos;
    private javax.swing.JPanel Estado;
    private javax.swing.JPanel FechaAlta;
    private javax.swing.JPanel Horario;
    private javax.swing.JPanel IdEmpleado;
    private javax.swing.JPanel Materno;
    private javax.swing.JPanel Nombre;
    private javax.swing.JPanel PanelSexo;
    private javax.swing.JPanel Paterno;
    private javax.swing.JPanel Puesto;
    private javax.swing.JPanel Salario;
    public javax.swing.ButtonGroup Sexo;
    private javax.swing.JPanel Titulo;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<String> cmbEstado;
    public com.toedter.calendar.JDateChooser dateFechaAlta;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JRadioButton radioH;
    public javax.swing.JRadioButton radioM;
    public javax.swing.JSpinner spnSalario;
    public javax.swing.JTextField txtHorario;
    public javax.swing.JLabel txtIdEmpleado;
    public javax.swing.JTextField txtMaterno;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPaterno;
    public javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
